// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-connected/HomeConnected.tsx": () => import("../components/mockups/home-connected/HomeConnected.tsx"),
  "./components/mockups/waiting-room/WaitingRoom.tsx": () => import("../components/mockups/waiting-room/WaitingRoom.tsx"),
  "./components/mockups/waiting-room-copy-ppHYBD-p/WaitingRoomCopyPpHYBDP.tsx": () => import("../components/mockups/waiting-room-copy-ppHYBD-p/WaitingRoomCopyPpHYBDP.tsx"),
  "./components/mockups/signup-complete/SignupComplete.tsx": () => import("../components/mockups/signup-complete/SignupComplete.tsx")
};
